// Generated by CoffeeScript 1.4.0
var AccountPayment, CancelSubscription, EatLater, EatNow, EatNowBoloco, EatNowMap, FullMenu, GraphCtrl, Home, LunchDate, ManageSubscriptions, Subscribe, SubscriptionActive, Today, Tomorrow, app;

app = angular.module("app", []);

Home = function($scope) {
  $scope.eatNow = function() {
    return console.log("eat");
  };
  $scope.eatLater = function() {};
  $scope.manageSubscriptions = function() {};
  $scope.accountAndPayment = function() {};
  return $scope.notificationsAndOptions = function() {};
};

EatNow = function($scope) {};

EatLater = function($scope) {};

EatNowMap = function($scope) {};

Today = function($scope) {};

Tomorrow = function($scope) {};

Subscribe = function($scope) {};

LunchDate = function($scope) {};

ManageSubscriptions = function($scope) {};

AccountPayment = function($scope) {};

EatNowBoloco = function($scope) {};

SubscriptionActive = function($scope) {};

CancelSubscription = function($scope) {};

FullMenu = function($scope) {};

GraphCtrl = function($scope) {};
